First code review
moka-guys/archer_archiving pull request #1
Opened 2022-07-15 09:50 UTC by rebeccahaines1

2022-07-18 14:39 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_archiving/1)* status: 0 of 3 files reviewed, 22 unresolved discussions (waiting on @aledj2 and @rebeccahaines1)

___
*[`archer_archive_script.py` line 58 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FlMzd-Jiz4zCgFhU6:-N7FlMze0FtwCFxSG5Od:b-q3x2fm) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L58)):*
> ```Python
> 				self.logger("Archer project not identified.", "Archer archive")
> 
> 	def check_previously_archived(self,archer_project_ID):
> ```

just a Q - having one file is probably more efficient than one file per project, but what if this one file is deleted/renamed etc by mistake? would have a bigger effect than one file being lost?
Maybe these files could be used as a logfile eg to capture the stdout from the upload agent (I haven't read this all the way through at the time of typing!)
___
*[`archer_archive_script.py` line 67 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7Gj1FZ4YTjHNqRZb4j:-N7Gj1FZ4YTjHNqRZb4k:bulo7uc) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L67)):*
> ```Python
> 			archived_runs_list = archived_runs.read().splitlines()
> 			# check if project is on list of previously archived projects. Return True if it is, False if not
> 			if archer_project_ID in archived_runs_list:
> ```

might be a extreme edge case but what if we are looking to archive project 123 and we have project 1234 in the archived list - would this be skipped? I realise this is very unlikely to be a realistic scenario.

similarly would we ever have an analysis id > 9999? (again probably unlikely!)fcleany
___
*[`archer_archive_script.py` line 88 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7Flkh3C1XyJEHN84kS:-N7Flkh3C1XyJEHN84kT:b-a21pk1) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L88)):*
> ```Python
> 		if config.testing:
> 			cmd = "archer_pw=$(<%s); \
> 				sshpass -p $archer_pw ssh s_archerupload@grpvgaa01.viapath.local ls %s/%s" % (
> ```

have a single place holder here and use os.path.join(path_to_test_folder, archer_project_ID) in the brackets - means you don't have any issues with trailing slashes

(same below)



_Code quote:_
```Python
%s/%s
```
___
*[`archer_archive_script.py` line 102 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FmFfJ4xNMCJdsLwHR:-N7FmFfJ4xNMCJdsLwHS:b-hibd2s) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L102)):*
> ```Python
> 		archer_tar = archer_project_ID + ".tar.gz"
> 		for file in out.split("\n"):
> 			if file == archer_tar:
> ```

would `if os.path.isfile(archer_tar)` simplify things here? you're using file twice in the same if loop below

I wonder if os.path.listdir would also help here rather than using subprocess.

edit -> probably should ignore this as you need subprocess to ssh on first!
___
*[`archer_archive_script.py` line 112 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FnAVV6UtNTFtEqCu4:-N7FnAVV6UtNTFtEqCu5:bo2hp39) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L112)):*
> ```Python
> 			else:
> 				self.logger("Project %s not yet archived in Archer software. Move on to next project" % (archer_project_ID), "Archer archive")
> 				return False,"none"
> ```

None rather than "none"?
___
*[`archer_archive_script.py` line 114 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FvkNW8Z08DPnBYF_G:-N7FvkNW8Z08DPnBYF_H:b-2xm2gj) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L114)):*
> ```Python
> 				return False,"none"
> 
> 	def list_archer_project_files(self,archer_project_ID):
> ```

this only returns fastqs?
___
*[`archer_archive_script.py` line 121 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FunW35sKbpZ-3r1Z3:-N7FunW4CCgZKsZjHsYp:b-9yu4kz) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L121)):*
> ```Python
> 		"""
> 		# echo $? returns exit status of last command, non zero means it's failed
> 		fastq_loc_file = "%s/%s_fastq_loc.txt" % (config.fastq_locations_folder,archer_project_ID)
> ```

as above, use os.path.join in the variable to be passed in



_Code quote:_
```Python
%s/%s
```
___
*[`archer_archive_script.py` line 124 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FuxE6C9mySQCEYvgA:-N7FuxE79goKEBQkqsPX:b-wryi41) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L124)):*
> ```Python
> 		if config.testing: #point to analysis_test_folder
> 			cmd = "archer_pw=$(<%s); \
> 				sshpass -p $archer_pw ssh s_archerupload@grpvgaa01.viapath.local ls -l %s/%s > %s; echo $?" % (
> ```

os.path.join()



_Code quote:_
```Python
%s/%s
```
___
*[`archer_archive_script.py` line 131 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7Fxb0y3F8KCqcINBMm:-N7Fxb0y3F8KCqcINBMn:b-wryi41) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L131)):*
> ```Python
> 		else:
> 			cmd = "archer_pw=$(<%s); \
> 				sshpass -p $archer_pw ssh s_archerupload@grpvgaa01.viapath.local ls -l %s/%s > %s; echo $?" % (
> ```

os.path.join()



_Code quote:_
```Python
s/%s
```
___
*[`archer_archive_script.py` line 140 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7Fxu4CACGxDr8ScpRC:-N7Fxu4CACGxDr8ScpRD:b6tnid3) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L140)):*
> ```Python
> 		if self.success_in_stdout(out.rstrip(), "0"):
> 			self.logger("Fastq locations file for project %s generated." % (archer_project_ID), "Archer archive")
> 			return True,fastq_loc_file
> ```

could set fastq_loc_file = False at the start and just return this. Then when calling this module it's just if list_archer_projects_files: (as list_archer_projects_files
___
*[`archer_archive_script.py` line 214 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7GLiCX5zSQBqCaLEzR:-N7GLiCX5zSQBqCaLEzS:b-m0wnw) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L214)):*
> ```Python
> 		"""
> 		# search DNAnexus for project matching project_adx (ADX###)
> 		cmd = config.source_command+";dx find projects --name='*%s*' --auth-token %s" % (project_adx,config.Nexus_API_Key)
> ```

if we ADX001 and then we have a rerun ADX001_rerun would this return both? 
if we were archiving ADX001_rerun that'd be ok as it's only match one, but ADX_001 would match two projects

What if we removed the wildcard form the end? eg *ADX001 none *ADX001*?

Do we ever get runs with >1 library eg ADX001 and ADX002?
___
*[`archer_archive_script.py` line 219 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7GLTGW5kavnYAaImgX:-N7GLTGW5kavnYAaImgY:b-vgvue) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L219)):*
> ```Python
> 		# count number of projects returned. If unable to identify a single matching project return error
> 		# note: if one project found len(matchingprojects)=2 because there is a newline 
> 		matching_projects = out.split("\n")
> ```

does this work ? out.rstrip().split("\n") 
___
*[`archer_archive_script.py` line 223 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7GMAM90fF17wWFRmEU:-N7GMAM90fF17wWFRmEV:b- [...]

2022-07-21 14:39 UTC, rebeccahaines1 reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_archiving/1)* status: 0 of 5 files reviewed, 22 unresolved discussions (waiting on @aledj2 and @rebeccahaines1)

___
*[`archer_archive_script.py` line 58 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FlMzd-Jiz4zCgFhU6:-N7KNYOW562lGxbTg0tM:brl3ybi) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L58)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

just a Q - having one file is probably more efficient than one file per project, but what if this one file is deleted/renamed etc by mistake? would have a bigger effect than one file being lost?
Maybe these files could be used as a logfile eg to capture the stdout from the upload agent (I haven't read this all the way through at the time of typing!)


</blockquote></details>

I've changed the cleanup function so the fastq_locations.txt file is not deleted. These files can be used to regenerate the list of previously archived files
___
*[`archer_archive_script.py` line 67 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7Gj1FZ4YTjHNqRZb4j:-N7H-4np641BBvEVHftU:bjmbz3t) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L67)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

might be a extreme edge case but what if we are looking to archive project 123 and we have project 1234 in the archived list - would this be skipped? I realise this is very unlikely to be a realistic scenario.

similarly would we ever have an analysis id > 9999? (again probably unlikely!)fcleany
</blockquote></details>

if archer project id is not 4 characters this would cause issues with other aspects of the script. I can check with Archer whether this is likely- though we've got about 5000 runs before we hit that problem...
___
*[`archer_archive_script.py` line 88 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7Flkh3C1XyJEHN84kS:-N7GysMD2BSnc34T9cuc:bb7f2mf) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L88)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

have a single place holder here and use os.path.join(path_to_test_folder, archer_project_ID) in the brackets - means you don't have any issues with trailing slashes

(same below)
</blockquote></details>

done
___
*[`archer_archive_script.py` line 102 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FmFfJ4xNMCJdsLwHR:-N7H01x96IQFrgcZxiB9:bancs1e) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L102)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

would `if os.path.isfile(archer_tar)` simplify things here? you're using file twice in the same if loop below

I wonder if os.path.listdir would also help here rather than using subprocess.

edit -> probably should ignore this as you need subprocess to ssh on first!
</blockquote></details>

considered renaming one iteration of file in this nested loop, but at the moment I think it makes more sense to use file twice because it's looking at the same thing, just pulling different information out in the nested loop.
___
*[`archer_archive_script.py` line 112 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FnAVV6UtNTFtEqCu4:-N7H0O-M8JtlwirCIgdo:bb7f2mf) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L112)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

None rather than "none"?
</blockquote></details>

done
___
*[`archer_archive_script.py` line 114 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FvkNW8Z08DPnBYF_G:-N7H0SzY4ebMJxBoUoWB:b-orl2rd) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L114)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

this only returns fastqs?
</blockquote></details>

no it lists all files in the folder. It's mainly needed to record the symlink locations of the fastqs, but it useful as a sense check to have all the file locations and associated permissions
___
*[`archer_archive_script.py` line 121 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FunW35sKbpZ-3r1Z3:-N7H0yil1I_MZll9Od_X:bb7f2mf) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L121)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

as above, use os.path.join in the variable to be passed in
</blockquote></details>

done
___
*[`archer_archive_script.py` line 124 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FuxE6C9mySQCEYvgA:-N7H1-3d1-lyx_fCCzrD:bb7f2mf) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L124)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

os.path.join()
</blockquote></details>

done
___
*[`archer_archive_script.py` line 131 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7Fxb0y3F8KCqcINBMm:-N7H1-zh2wtKc1w8a0x-:bb7f2mf) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L131)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

os.path.join()
</blockquote></details>

done
___
*[`archer_archive_script.py` line 140 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7Fxu4CACGxDr8ScpRC:-N7L8z3Z0ppvMOeGwSgs:bhfh1jn) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L140)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

could set fastq_loc_file = False at the start and just return this. Then when calling this module it's just if list_archer_projects_files: (as list_archer_projects_files
</blockquote></details>

changed so the function returns the file name or None and using that when calling it later
___
*[`archer_archive_script.py` line 214 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7GLiCX5zSQBqCaLEzR:-N7LAHvu5MmqYYizdfam:bn4gdop) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L214)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

if we ADX001 and then we have a rerun ADX001_rerun would this return both? 
if we were archiving ADX001_rerun that'd be ok as it's only match one, but ADX_001 would match two projects

What if we removed the wildcard form the end? eg *ADX001 none *ADX001*?

Do we ever get runs with >1 library eg ADX001 and ADX002?
</blockquote></details>

so yes I think this would return both ADX001 and ADX001_rerun. However, the way the script accesses the project name ADX### (in check_project_archived) means it wouldn't have ADX001_rerun as it takes the section before the first "_". This instance should be very rare, and would need to be handled by a manual upload to DNAnexus and manual clean up, as well as by asking the cancer team to ensure any renamed runs don't have "_" in them, so use ADX001rerun or ADX001b etc. This is what they have done in the past anyway. 

We do sometimes get ADX001_ADX002 in the same run, though not for a long time, so if we took out the second wildcard this wouldn't successfully archive both runs. Going to leave it a [...]

2022-07-22 16:36 UTC, aledj2 requested changes
> Reviewed 1 of 3 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_archiving/1)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @aledj2 and @rebeccahaines1)

___
*[`archer_archive_script.py` line 102 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FmFfJ4xNMCJdsLwHR:-N7abhlbAneb-FiGeZ2x:b-ygtio0) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L102)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

considered renaming one iteration of file in this nested loop, but at the moment I think it makes more sense to use file twice because it's looking at the same thing, just pulling different information out in the nested loop.
</blockquote></details>

ok- after re-reading his could do something like the below to avoid iterating over lists multiple times. In this case probably has no real performance benefit. (see also list filter function)



_Code snippet:_
```Python
if archer_tar in out.split("/n"):
	for file in out.split("/n"):
		if file.startswith...
```
___
*[`archer_archive_script.py` line 144 at r3](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7akmVdEWvhxZeZLbt6:-N7akmVdEWvhxZeZLbt7:b-vec1a2) ([raw file](https://github.com/moka-guys/archer_archiving/blob/70de3471d42ed38aa9a987ea40c4cce93a2c3659/archer_archive_script.py#L144)):*
> ```Python
> 		create txt file with ls -l of the archer project folder
> 		takes archer project ID (####) as input
> 		Returns True or False and the path of the fastq locations file that is created
> ```

not accurate anymore - can you check any other doc strings that have been changes in this way?

Can this return a list? Rather than None could be an empty list (which is also seen as None. - ties in with other comments on line 450 (sorry!)



_Code quote:_
```Python
Returns True or False and the path of the fastq locations file that is created
```
___
*[`archer_archive_script.py` line 380 at r3](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7aiFpIB1Q_wVsJlAqn:-N7aiFpIB1Q_wVsJlAqo:b-qup0ha) ([raw file](https://github.com/moka-guys/archer_archiving/blob/70de3471d42ed38aa9a987ea40c4cce93a2c3659/archer_archive_script.py#L380)):*
> ```Python
> 		path_to_project_tar = os.path.join(config.copy_location,"%s.tar.gz" % (archer_project_ID))
> 		# command to delete the downloaded fastq files
> 		cmd = "rm -r %s;rm %s; echo $?" % (path_to_project_folder,path_to_project_tar)
> ```

do you think it's worth doing this in two steps so we can test both steps?
___
*[`archer_archive_script.py` line 447 at r3](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7aiiWV9vYQMuJ3kUxg:-N7aiiWV9vYQMuJ3kUxh:bn3mlyq) ([raw file](https://github.com/moka-guys/archer_archiving/blob/70de3471d42ed38aa9a987ea40c4cce93a2c3659/archer_archive_script.py#L447)):*
> ```Python
> 					# check if project archived on archer, return project name (ADX##) if so
> 					adx_project_name = self.check_project_archived(project)
> 					if adx_project_name != None:
> ```

could just do if self.check_project_archived(project) - I don't think adx_project_name is used later?



_Code quote:_
```Python
					adx_project_name = self.check_project_archived(project)
					if adx_project_name != None:
```
___
*[`archer_archive_script.py` line 450 at r3](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7aj3qw1xOl3G5T-7C1:-N7aj3qw1xOl3G5T-7C2:b-nsor64) ([raw file](https://github.com/moka-guys/archer_archiving/blob/70de3471d42ed38aa9a987ea40c4cce93a2c3659/archer_archive_script.py#L450)):*
> ```Python
> 						# generate file listing locations of files in the archer project folder
> 						list_filename = self.list_archer_project_files(project) 
> 						if list_filename != None:
> ```

if convert list_archer_project_files(project)  to output a list could do:



_Code snippet:_
```Python
files_to_upload = self.list_archer_project_files(project) 
if files_to_upload:
```


<!-- Sent from Reviewable.io -->

2022-07-25 15:13 UTC, rebeccahaines1 reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_archiving/1)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @aledj2)

___
*[`archer_archive_script.py` line 102 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7FmFfJ4xNMCJdsLwHR:-N7pQnnz3JzgwzSsEZd0:bb7f2mf) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L102)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

ok- after re-reading his could do something like the below to avoid iterating over lists multiple times. In this case probably has no real performance benefit. (see also list filter function)
</blockquote></details>

done
___
*[`archer_archive_script.py` line 291 at r1](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7GiOxT1Y8AAxaCLgtQ:-N7pQjRa1sDWji_bwvTw:bb7f2mf) ([raw file](https://github.com/moka-guys/archer_archiving/blob/cd072c35911e606250f271ba896c26efa32bd00b/archer_archive_script.py#L291)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we improve this? using os.path.join and add picked_up_files into config or something? (feel free to ignore this!)
</blockquote></details>

done
___
*[`archer_archive_script.py` line 144 at r3](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7akmVdEWvhxZeZLbt6:-N7ox8Ly-DbOZ9zMp8JP:b-896fix) ([raw file](https://github.com/moka-guys/archer_archiving/blob/70de3471d42ed38aa9a987ea40c4cce93a2c3659/archer_archive_script.py#L144)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

not accurate anymore - can you check any other doc strings that have been changes in this way?

Can this return a list? Rather than None could be an empty list (which is also seen as None. - ties in with other comments on line 450 (sorry!)
</blockquote></details>

Done.
___
*[`archer_archive_script.py` line 380 at r3](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7aiFpIB1Q_wVsJlAqn:-N7pMRbGECaLH-Jb_RH1:b91wu64) ([raw file](https://github.com/moka-guys/archer_archiving/blob/70de3471d42ed38aa9a987ea40c4cce93a2c3659/archer_archive_script.py#L380)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

do you think it's worth doing this in two steps so we can test both steps?
</blockquote></details>

I've changed this to one step to delete both files as they're in the same location and have the project ID in their name. If this step completes successfully then the script will proceed, and if not there will need to be some manual deletion steps and troubleshooting.
___
*[`archer_archive_script.py` line 447 at r3](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7aiiWV9vYQMuJ3kUxg:-N7pNwsP0vbsTMe2EAl7:b-dpohsy) ([raw file](https://github.com/moka-guys/archer_archiving/blob/70de3471d42ed38aa9a987ea40c4cce93a2c3659/archer_archive_script.py#L447)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

could just do if self.check_project_archived(project) - I don't think adx_project_name is used later?
</blockquote></details>

it is- it's needed as an input on lines 476,482 and 484 (it's the human readable project name ADX###)
___
*[`archer_archive_script.py` line 450 at r3](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7aj3qw1xOl3G5T-7C1:-N7pPwoD5aHxQM1hLtTw:bb7f2mf) ([raw file](https://github.com/moka-guys/archer_archiving/blob/70de3471d42ed38aa9a987ea40c4cce93a2c3659/archer_archive_script.py#L450)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

if convert list_archer_project_files(project)  to output a list could do:
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-07-25 15:55 UTC, aledj2 requested changes
> Reviewed 1 of 4 files at r2, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_archiving/1)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @aledj2 and @rebeccahaines1)

___
*[`archer_archive_script.py` line 262 at r4](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7q2whh9PVZvpx8t0V9:-N7q2whi1Xym-0Xy9g0U:b3fbbx8) ([raw file](https://github.com/moka-guys/archer_archiving/blob/1f8a93422094099819fa51e3af0c54388a6c5c53/archer_archive_script.py#L262)):*
> ```Python
> 		list_of_files = " ".join(file_list)
> 		# generate command to upload file to DNAnexus project
> 		cmd = "%s --auth-token %s --project %s %s" % (
> ```

I've just realised we use the --do-not-compress flag when using the upload agent . eg https://github.com/moka-guys/automate_demultiplex/blob/ad92b08bb00457760f66fc91c1b3e3b76d3460e1/upload_and_setoff_workflows.py#L876


<!-- Sent from Reviewable.io -->

2022-07-25 16:05 UTC, rebeccahaines1 reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_archiving/1)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[`archer_archive_script.py` line 262 at r4](https://reviewable.io/reviews/moka-guys/archer_archiving/1#-N7q2whh9PVZvpx8t0V9:-N7q4AMU80_S6mhhffK8:bqzvhgr) ([raw file](https://github.com/moka-guys/archer_archiving/blob/1f8a93422094099819fa51e3af0c54388a6c5c53/archer_archive_script.py#L262)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I've just realised we use the --do-not-compress flag when using the upload agent . eg https://github.com/moka-guys/automate_demultiplex/blob/ad92b08bb00457760f66fc91c1b3e3b76d3460e1/upload_and_setoff_workflows.py#L876
</blockquote></details>

Done- I don't think it does re-compress the tar.gz archive- when testing the one I've just uploaded is the same file size as one from earlier uploaded without the flag. The text fastq locations file is larger though.


<!-- Sent from Reviewable.io -->

2022-07-25 16:12 UTC, aledj2 approved these changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/archer_archiving/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rebeccahaines1)



<!-- Sent from Reviewable.io -->

2022-07-25 16:12 UTC, merged